name: Deploy to Azure App Service

on:
  push:
    branches:
      - testing
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Install backend dependencies
      run: cd backend && npm install
      
    - name: Install frontend dependencies and build
      run: cd frontend && npm install && npm run build
      
    - name: Login to Azure
      uses: azure/login@v1
      with:
        creds: '{"clientId":"${{ secrets.AZUREAPPSERVICE_CLIENTID_56E3EB9F467448219F20FBBA11ED0530C }}","clientSecret":"${{ secrets.AZUREAPPSERVICE_CLIENTSECRET_PLACEHOLDER }}","subscriptionId":"${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_4B75E09993CF42A8B38B2C375228C974 }}","tenantId":"${{ secrets.AZUREAPPSERVICE_TENANTID_3DFBC115F0354DDEA2FA3198D9EDDC0C }}"}'
        
    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ secrets.AZURE_WEBAPP_NAME }}
        package: .
